services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.55.1-jammy
    user: "${PLAYWRIGHT_UID:-1000}:${PLAYWRIGHT_GID:-1000}"
    working_dir: /workspace
    volumes:
      - .:/workspace:delegated
      - ./.playwright/node_modules:/workspace/node_modules
    environment:
      NUXT_TELEMETRY_DISABLED: "1"
      PLAYWRIGHT_VERSION: "1.47.0"
      PLAYWRIGHT_BROWSERS: "${PLAYWRIGHT_BROWSERS:-}"
      PLAYWRIGHT_BROWSER: "${PLAYWRIGHT_BROWSER:-}"
      NUXT_CONTENT_LOCAL_CACHE_DIR: "${NUXT_CONTENT_LOCAL_CACHE_DIR:-/tmp/nuxt-content-cache}"
    entrypoint: ["/bin/bash", "/workspace/docker/playwright/entrypoint.sh"]
    shm_size: 1gb
