x-common-environment: &common-env
  NUXT_TELEMETRY_DISABLED: "1"
  ENABLE_BROWSER_TESTS: "false"

x-common-volumes: &common-volumes
  - .:/app
  - node_modules:/app/node_modules
  - pnpm-store:/root/.local/share/pnpm
  - playwright-cache:/ms-playwright

services:
  app:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes: *common-volumes
    environment:
      <<: *common-env
      VITE_LOG_LEVEL: info
    ports:
      - "3000:3000"
    tty: true

  test:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:unit"]
    environment:
      <<: *common-env
      CI: "1"
    volumes: *common-volumes
    profiles: ["tests"]

  coverage:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["bash", "-lc", "ENABLE_BROWSER_TESTS=false pnpm test:coverage"]
    environment:
      <<: *common-env
      CI: "1"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
      - ./reports:/app/reports
    profiles: ["tests"]

  e2e:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:e2e:ci"]
    environment:
      <<: *common-env
      CI: "1"
    volumes: *common-volumes
    profiles: ["tests"]

  performance:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:performance"]
    environment:
      <<: *common-env
      CI: "1"
      LHCI_RUNNER_UID: "${LOCAL_UID:-1000}"
      LHCI_RUNNER_GID: "${LOCAL_GID:-1000}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
      - ./reports:/app/reports
      - ./test-results:/app/test-results
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb
    profiles: ["tests"]

volumes:
  node_modules:
  pnpm-store:
  playwright-cache:
