x-common-environment: &common-env
  NUXT_TELEMETRY_DISABLED: "1"
  ENABLE_BROWSER_TESTS: "false"

services:
  app:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
    environment:
      <<: *common-env
      VITE_LOG_LEVEL: info
      PORT: "3000"
      VITE_HMR_HOST: "localhost"
      VITE_HMR_PORT: "3000"
      VITE_HMR_CLIENT_PORT: "3000"
      VITE_ALLOWED_HOSTS: "localhost"
      VITE_DISABLE_HMR: "0"
    ports:
      - "3000:3000"
    tty: true

  test:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:unit"]
    environment:
      <<: *common-env
      CI: "1"
      SKIP_BOOTSTRAP: "1"
    volumes:
      - .:/app
      - test_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
    profiles: ["tests"]

  coverage:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["bash", "-lc", "ENABLE_BROWSER_TESTS=false pnpm test:coverage"]
    environment:
      <<: *common-env
      CI: "1"
      SKIP_BOOTSTRAP: "1"
    volumes:
      - .:/app
      - coverage_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
      - ./reports:/app/reports
    profiles: ["tests"]

  e2e:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:e2e:ci"]
    environment:
      <<: *common-env
      CI: "1"
      SKIP_BOOTSTRAP: "1"
    volumes:
      - .:/app
      - e2e_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
    profiles: ["tests"]

  performance:
    build:
      context: .
    image: portfolio-dev:latest
    entrypoint: ["app-entrypoint.sh"]
    command: ["pnpm", "test:performance"]
    environment:
      <<: *common-env
      CI: "1"
      SKIP_BOOTSTRAP: "1"
      LHCI_RUNNER_UID: "${LOCAL_UID:-1000}"
      LHCI_RUNNER_GID: "${LOCAL_GID:-1000}"
    volumes:
      - .:/app
      - performance_node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm
      - playwright-cache:/ms-playwright
      - ./reports:/app/reports
      - ./test-results:/app/test-results
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb
    profiles: ["tests"]

volumes:
  app_node_modules:
  test_node_modules:
  coverage_node_modules:
  e2e_node_modules:
  performance_node_modules:
  pnpm-store:
  playwright-cache:
