name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Nuxt content cache
        run: rm -rf .data

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest unit suite (docker)
        run: docker compose run --rm test pnpm vitest run

  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Nuxt content cache
        run: rm -rf .data

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Playwright volume
        run: mkdir -p .playwright/node_modules

      - name: Run dockerized Playwright UI suite
        env:
          ENABLE_BROWSER_TESTS: 'true'
          NUXT_CONTENT_LOCAL_CACHE_DIR: "/tmp/content-cache-${{ github.run_id }}-${{ github.run_attempt }}"
        run: pnpm test:ui:container

      - name: Cleanup Playwright containers
        if: always()
        run: docker compose -f docker-compose.playwright.yml down --remove-orphans || true

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Nuxt content cache
        run: rm -rf .data

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate static site & validate HTML
        env:
          SKIP_PRUNE: '1'
        run: pnpm run validate:html

      - name: Enforce bundle budgets
        run: pnpm run check:bundle

      - name: Prune build artifacts
        run: pnpm run prune:artifacts

      - name: Prepare Playwright volume
        run: mkdir -p .playwright/node_modules

      - name: Run accessibility audits (docker)
        env:
          ENABLE_BROWSER_TESTS: 'true'
          PLAYWRIGHT_BROWSERS: 'chromium'
          SKIP_GENERATE: '1'
          NUXT_CONTENT_LOCAL_CACHE_DIR: "/tmp/content-cache-${{ github.run_id }}-${{ github.run_attempt }}-a11y"
        run: pnpm test:accessibility:container

      - name: Run Lighthouse performance checks (docker)
        env:
          PLAYWRIGHT_BROWSERS: 'chromium'
          PLAYWRIGHT_UID: '0'
          PLAYWRIGHT_GID: '0'
          LOCAL_PREVIEW_LOG: '/workspace/reports/local-preview.log'
          NUXT_CONTENT_LOCAL_CACHE_DIR: "/tmp/content-cache-${{ github.run_id }}-${{ github.run_attempt }}-lhci"
        run: pnpm test:performance:container

      - name: Cleanup Playwright containers
        if: always()
        run: docker compose -f docker-compose.playwright.yml down --remove-orphans || true
