name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Nuxt content cache
        run: rm -rf .data

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest unit suite
        env:
          ENABLE_BROWSER_TESTS: 'false'
        run: pnpm test:unit

      - name: Run dockerized Playwright UI suite
        env:
          ENABLE_BROWSER_TESTS: 'true'
        run: pnpm test:ui:container

      - name: Cleanup Playwright containers
        if: always()
        run: docker compose -f docker-compose.playwright.yml down --remove-orphans || true
