name: Deploy to Cloudflare Pages

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-preview'

permissions:
  contents: write
  deployments: write

concurrency:
  group: cloudflare-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
      IS_PREVIEW: ${{ contains(github.ref, '-preview') }}
      CF_DEPLOY_BRANCH: ${{ contains(github.ref, '-preview') && 'preview' || 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Nuxt content cache
        run: rm -rf .data

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Run unit tests with coverage
        env:
          ENABLE_BROWSER_TESTS: 'false'
        run: pnpm test:coverage

      - name: Generate static site
        run: pnpm generate

      - name: Run responsive UI suite (desktop/tablet/mobile)
        env:
          ENABLE_BROWSER_TESTS: 'true'
          PLAYWRIGHT_NODE_VERSION: '22.20.0'
        run: pnpm test:ui:container

      - name: Run Playwright E2E suite
        env:
          SKIP_GENERATE: '1'
        run: pnpm test:e2e:ci

      - name: Run Lighthouse performance checks
        env:
          SKIP_GENERATE: '1'
        run: pnpm test:performance

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          directory: .output/public
          branch: ${{ env.CF_DEPLOY_BRANCH }}

      - name: Publish GitHub release notes
        if: ${{ env.IS_PREVIEW != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
